"""Initial migration

Revision ID: 353b8f50897a
Revises: 
Create Date: 2026-06-03 23:11:42.866764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '353b8f50897a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('country', sa.String(length=80), server_default='Nepal', nullable=False),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('image_public_id', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cities_name'), 'cities', ['name'], unique=True)
    op.create_table('coupons',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('discount_type', sa.Enum('percentage', 'fixed', name='discount_type'), nullable=False),
    sa.Column('discount_value', sa.Float(), nullable=False),
    sa.Column('min_booking_amount', sa.Float(), nullable=False),
    sa.Column('max_discount_amount', sa.Float(), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usage_limit', sa.Integer(), nullable=True),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('applicable_hotels', sa.ARRAY(sa.UUID()), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coupons_code'), 'coupons', ['code'], unique=True)
    op.create_table('facilities',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('icon', sa.String(length=80), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('heroes',
    sa.Column('image', sa.String(length=500), nullable=False),
    sa.Column('image_public_id', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('sub_title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_heroes_active'), 'heroes', ['active'], unique=False)
    op.create_table('locations',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=60), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('city_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_city_id'), 'locations', ['city_id'], unique=False)
    op.create_index(op.f('ix_locations_name'), 'locations', ['name'], unique=False)
    op.create_index(op.f('ix_locations_type'), 'locations', ['type'], unique=False)
    op.create_table('otps',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('verification', 'password_reset', 'email_change', name='otp_type'), nullable=False),
    sa.Column('new_email', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otps_email'), 'otps', ['email'], unique=False)
    op.create_index('ix_otps_email_type', 'otps', ['email', 'type'], unique=False)
    op.create_table('services',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('icon', sa.String(length=80), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('travel_packages',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('duration_nights', sa.Integer(), nullable=False),
    sa.Column('price_per_person', sa.Float(), nullable=False),
    sa.Column('discount_price', sa.Float(), nullable=True),
    sa.Column('inclusions', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('exclusions', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('itinerary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hotel_ids', sa.ARRAY(sa.UUID()), nullable=False),
    sa.Column('city_ids', sa.ARRAY(sa.UUID()), nullable=False),
    sa.Column('start_city_id', sa.UUID(), nullable=True),
    sa.Column('end_city_id', sa.UUID(), nullable=True),
    sa.Column('group_size_min', sa.Integer(), nullable=False),
    sa.Column('group_size_max', sa.Integer(), nullable=False),
    sa.Column('difficulty_level', sa.Enum('easy', 'moderate', 'challenging', name='difficulty_level'), nullable=False),
    sa.Column('season_start', sa.Date(), nullable=True),
    sa.Column('season_end', sa.Date(), nullable=True),
    sa.Column('featured_image', sa.String(length=500), nullable=True),
    sa.Column('gallery_images', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'upcoming', name='travel_package_status'), nullable=False),
    sa.Column('total_bookings', sa.Integer(), nullable=False),
    sa.Column('average_rating', sa.Float(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_travel_packages_name'), 'travel_packages', ['name'], unique=False)
    op.create_index(op.f('ix_travel_packages_price_per_person'), 'travel_packages', ['price_per_person'], unique=False)
    op.create_index(op.f('ix_travel_packages_slug'), 'travel_packages', ['slug'], unique=True)
    op.create_index(op.f('ix_travel_packages_status'), 'travel_packages', ['status'], unique=False)
    op.create_table('users',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('image_public_id', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('user', 'owner', 'admin', name='user_role'), server_default='user', nullable=False),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('travel_style', sa.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('favorite_hotels', sa.ARRAY(sa.UUID()), server_default='{}', nullable=False),
    sa.Column('wishlist', sa.ARRAY(sa.UUID()), server_default='{}', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=False)
    op.create_table('activity_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_action_type'), 'activity_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_activity_logs_timestamp'), 'activity_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_activity_logs_user_id'), 'activity_logs', ['user_id'], unique=False)
    op.create_table('blogs',
    sa.Column('title', sa.String(length=220), nullable=False),
    sa.Column('slug', sa.String(length=240), nullable=False),
    sa.Column('image', sa.String(length=500), nullable=False),
    sa.Column('image_public_id', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blogs_published'), 'blogs', ['published'], unique=False)
    op.create_index(op.f('ix_blogs_slug'), 'blogs', ['slug'], unique=True)
    op.create_table('chat_sessions',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('session_key', sa.String(length=80), nullable=False),
    sa.Column('messages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('turns', sa.Integer(), nullable=False),
    sa.Column('last_intent', sa.String(length=80), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_session_key'), 'chat_sessions', ['session_key'], unique=True)
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_table('hotels',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('pan_number', sa.String(length=20), nullable=True),
    sa.Column('logo', sa.String(length=500), nullable=True),
    sa.Column('logo_public_id', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('resort', 'hostel', 'hotel', 'homestay', 'other', name='hotel_type'), nullable=False),
    sa.Column('status', sa.Enum('approved', 'pending', 'rejected', name='hotel_status'), nullable=False),
    sa.Column('city_id', sa.UUID(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('street', sa.String(length=120), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('check_in_time', sa.Time(), nullable=False),
    sa.Column('check_out_time', sa.Time(), nullable=False),
    sa.Column('cancellation_policy', sa.Enum('free', 'flexible', 'moderate', 'strict', name='cancellation_policy'), nullable=False),
    sa.Column('cancellation_deadline_hours', sa.Integer(), nullable=False),
    sa.Column('cancellation_fee_percentage', sa.Float(), nullable=False),
    sa.Column('tax_percentage', sa.Float(), nullable=False),
    sa.Column('service_charge_percentage', sa.Float(), nullable=False),
    sa.Column('min_advance_booking_days', sa.Integer(), nullable=False),
    sa.Column('max_advance_booking_days', sa.Integer(), nullable=False),
    sa.Column('min_stay_nights', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('average_review_rating', sa.Float(), nullable=False),
    sa.Column('total_reviews', sa.Integer(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('booking_count', sa.Integer(), nullable=False),
    sa.Column('popularity_score', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hotels_city_id'), 'hotels', ['city_id'], unique=False)
    op.create_index('ix_hotels_lat_lng', 'hotels', ['latitude', 'longitude'], unique=False)
    op.create_index(op.f('ix_hotels_latitude'), 'hotels', ['latitude'], unique=False)
    op.create_index(op.f('ix_hotels_longitude'), 'hotels', ['longitude'], unique=False)
    op.create_index(op.f('ix_hotels_name'), 'hotels', ['name'], unique=False)
    op.create_index(op.f('ix_hotels_owner_id'), 'hotels', ['owner_id'], unique=False)
    op.create_index(op.f('ix_hotels_popularity_score'), 'hotels', ['popularity_score'], unique=False)
    op.create_index(op.f('ix_hotels_status'), 'hotels', ['status'], unique=False)
    op.create_index('ix_hotels_status_city', 'hotels', ['status', 'city_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('booking_confirmed', 'booking_canceled', 'review_response', 'review_approved', 'payment_success', 'payment_failed', 'hotel_approved', 'hotel_rejected', 'travel_booking', 'system', name='notification_type'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_read'), 'notifications', ['read'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_jti'), 'refresh_tokens', ['jti'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('travel_bookings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('travel_date', sa.Date(), nullable=False),
    sa.Column('number_of_travelers', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('traveler_details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('special_requirements', sa.Text(), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=120), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'completed', 'cancelled', name='travel_booking_status'), nullable=False),
    sa.Column('payment_status', sa.Enum('pending', 'paid', 'refunded', 'failed', name='tb_payment_status'), nullable=False),
    sa.Column('payment_method', sa.Enum('esewa', 'khalti', 'cash', name='tb_payment_method'), nullable=True),
    sa.Column('payment_id', sa.String(length=200), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['travel_packages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_travel_bookings_package_id'), 'travel_bookings', ['package_id'], unique=False)
    op.create_index(op.f('ix_travel_bookings_user_id'), 'travel_bookings', ['user_id'], unique=False)
    op.create_table('hotel_facilities',
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('hotel_id', 'facility_id')
    )
    op.create_table('photos',
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('public_id', sa.String(length=255), nullable=True),
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('ai_tags', sa.Text(), nullable=True),
    sa.Column('ai_quality_score', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photos_hotel_id'), 'photos', ['hotel_id'], unique=False)
    op.create_table('policies',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hotel_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policies_hotel_id'), 'policies', ['hotel_id'], unique=False)
    op.create_table('rooms',
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('room_type', sa.Enum('single', 'double', 'suite', 'deluxe', 'family', 'other', name='room_type'), nullable=False),
    sa.Column('room_name', sa.String(length=120), nullable=False),
    sa.Column('number_of_rooms', sa.Integer(), nullable=False),
    sa.Column('bed_type', sa.Enum('single', 'double', 'queen', 'king', 'bunk', 'sofa', 'other', name='bed_type'), nullable=False),
    sa.Column('number_of_beds', sa.Integer(), nullable=False),
    sa.Column('smoking_policy', sa.Enum('smoking', 'non_smoking', 'both', name='smoking_policy'), nullable=False),
    sa.Column('base_price', sa.Float(), nullable=False),
    sa.Column('max_guest', sa.Integer(), nullable=False),
    sa.Column('room_size', sa.String(length=40), nullable=True),
    sa.Column('discount_percentage', sa.Float(), nullable=False),
    sa.Column('weekend_price', sa.Float(), nullable=True),
    sa.Column('festival_price', sa.Float(), nullable=True),
    sa.Column('images', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('amenities', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('view_type', sa.Enum('city', 'mountain', 'garden', 'pool', 'ocean', 'none', name='view_type'), nullable=False),
    sa.Column('floor_number', sa.Integer(), nullable=True),
    sa.Column('has_ac', sa.Boolean(), nullable=False),
    sa.Column('has_wifi', sa.Boolean(), nullable=False),
    sa.Column('has_tv', sa.Boolean(), nullable=False),
    sa.Column('has_minibar', sa.Boolean(), nullable=False),
    sa.Column('has_safe', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_base_price'), 'rooms', ['base_price'], unique=False)
    op.create_index(op.f('ix_rooms_hotel_id'), 'rooms', ['hotel_id'], unique=False)
    op.create_table('bookings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=True),
    sa.Column('check_in', sa.Date(), nullable=False),
    sa.Column('check_out', sa.Date(), nullable=False),
    sa.Column('num', sa.Integer(), nullable=False),
    sa.Column('guest_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('confirmed', 'pending', 'canceled', 'completed', name='booking_status'), nullable=False),
    sa.Column('payment_status', sa.Enum('pending', 'paid', 'refunded', 'failed', name='payment_status'), nullable=False),
    sa.Column('payment_method', sa.Enum('esewa', 'khalti', 'cash', name='payment_method'), nullable=True),
    sa.Column('payment_id', sa.String(length=200), nullable=True),
    sa.Column('base_price', sa.Float(), nullable=False),
    sa.Column('tax_amount', sa.Float(), nullable=False),
    sa.Column('service_charge', sa.Float(), nullable=False),
    sa.Column('discount_amount', sa.Float(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('coupon_code', sa.String(length=50), nullable=True),
    sa.Column('special_requests', sa.Text(), nullable=True),
    sa.Column('guest_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_check_in'), 'bookings', ['check_in'], unique=False)
    op.create_index(op.f('ix_bookings_check_out'), 'bookings', ['check_out'], unique=False)
    op.create_index('ix_bookings_hotel_dates_active', 'bookings', ['hotel_id', 'check_in', 'check_out'], unique=False, postgresql_where="status != 'canceled'")
    op.create_index(op.f('ix_bookings_hotel_id'), 'bookings', ['hotel_id'], unique=False)
    op.create_index(op.f('ix_bookings_payment_status'), 'bookings', ['payment_status'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    op.create_table('room_services',
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('room_id', 'service_id')
    )
    op.create_table('reviews',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('images', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('helpful_count', sa.Integer(), nullable=False),
    sa.Column('helpful_by', sa.ARRAY(sa.UUID()), nullable=False),
    sa.Column('reported', sa.Boolean(), nullable=False),
    sa.Column('owner_response', sa.Text(), nullable=True),
    sa.Column('owner_response_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='review_status'), nullable=False),
    sa.Column('sentiment', sa.Enum('positive', 'negative', 'neutral', name='sentiment'), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('topics', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id')
    )
    op.create_index(op.f('ix_reviews_hotel_id'), 'reviews', ['hotel_id'], unique=False)
    op.create_index(op.f('ix_reviews_status'), 'reviews', ['status'], unique=False)
    op.create_index(op.f('ix_reviews_user_id'), 'reviews', ['user_id'], unique=False)
    op.create_table('transactions',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('transaction_uuid', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.Enum('esewa', 'khalti', 'cash', name='txn_provider'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'paid', 'refunded', 'failed', name='txn_status'), nullable=False),
    sa.Column('ref_id', sa.String(length=100), nullable=True),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_booking_id'), 'transactions', ['booking_id'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_uuid'), 'transactions', ['transaction_uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_transaction_uuid'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_booking_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_reviews_user_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_status'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_hotel_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_table('room_services')
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_payment_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_hotel_id'), table_name='bookings')
    op.drop_index('ix_bookings_hotel_dates_active', table_name='bookings', postgresql_where="status != 'canceled'")
    op.drop_index(op.f('ix_bookings_check_out'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_check_in'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_rooms_hotel_id'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_base_price'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_policies_hotel_id'), table_name='policies')
    op.drop_table('policies')
    op.drop_index(op.f('ix_photos_hotel_id'), table_name='photos')
    op.drop_table('photos')
    op.drop_table('hotel_facilities')
    op.drop_index(op.f('ix_travel_bookings_user_id'), table_name='travel_bookings')
    op.drop_index(op.f('ix_travel_bookings_package_id'), table_name='travel_bookings')
    op.drop_table('travel_bookings')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_jti'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_read'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_hotels_status_city', table_name='hotels')
    op.drop_index(op.f('ix_hotels_status'), table_name='hotels')
    op.drop_index(op.f('ix_hotels_popularity_score'), table_name='hotels')
    op.drop_index(op.f('ix_hotels_owner_id'), table_name='hotels')
    op.drop_index(op.f('ix_hotels_name'), table_name='hotels')
    op.drop_index(op.f('ix_hotels_longitude'), table_name='hotels')
    op.drop_index(op.f('ix_hotels_latitude'), table_name='hotels')
    op.drop_index('ix_hotels_lat_lng', table_name='hotels')
    op.drop_index(op.f('ix_hotels_city_id'), table_name='hotels')
    op.drop_table('hotels')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_session_key'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_blogs_slug'), table_name='blogs')
    op.drop_index(op.f('ix_blogs_published'), table_name='blogs')
    op.drop_table('blogs')
    op.drop_index(op.f('ix_activity_logs_user_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_timestamp'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_action_type'), table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_travel_packages_status'), table_name='travel_packages')
    op.drop_index(op.f('ix_travel_packages_slug'), table_name='travel_packages')
    op.drop_index(op.f('ix_travel_packages_price_per_person'), table_name='travel_packages')
    op.drop_index(op.f('ix_travel_packages_name'), table_name='travel_packages')
    op.drop_table('travel_packages')
    op.drop_table('services')
    op.drop_index('ix_otps_email_type', table_name='otps')
    op.drop_index(op.f('ix_otps_email'), table_name='otps')
    op.drop_table('otps')
    op.drop_index(op.f('ix_locations_type'), table_name='locations')
    op.drop_index(op.f('ix_locations_name'), table_name='locations')
    op.drop_index(op.f('ix_locations_city_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_heroes_active'), table_name='heroes')
    op.drop_table('heroes')
    op.drop_table('facilities')
    op.drop_index(op.f('ix_coupons_code'), table_name='coupons')
    op.drop_table('coupons')
    op.drop_index(op.f('ix_cities_name'), table_name='cities')
    op.drop_table('cities')
    # ### end Alembic commands ###
